### ISSUE TITLE
Input wav file as a BytesIO object not working

### ISSUE THREAD

**Issue by kormoczi** [xinjli/allosaurus#39]
Hi,
I wanted to read the speech wav from a BytesIO object, but it does not work, because of the assert in the line 65 of app.py (filename should have a ".wav" extension). I have tried to give a filename to the BytesIO object, but it did not help either (do not really understand, why). If I comment this above mentioned line, then everything works well, but I would like to have a more appropriate / robust solution, which do not need the modification of the original code.
Do you have any suggestion or advice?
Thanks!

**Comment by xinjli** [comment]
Currently, the IO is using the native wave lib to open the file and read, but in the next version, we are thinking about using the torchaudio to handle the IO, which allows us to use other popular format (e.g: mp3). 

I am not sure whether torchaudio can handle BytesIO correctly, but I think should be supported at some point because I am personally sometimes using BytesIO myself

**Comment by kormoczi** [comment]
Hi @xinjli,
Maybe I was not clear enough... The wave lib works well, the only problem is, that there is a check for the file name in app.py, and this check / assert not handling the BytesIO objects correctly.

**Comment by xinjli** [comment]
Yeah, I think this is a reasonable suggestion. Can you make a pull request to bypass the file check when it is an instance of BytesIO objects?

**Comment by kormoczi** [comment]
Hi @xinjli,
I made a pull request, I hope everything is clear...

**Comment by xinjli** [comment]
Yeah, it was very clear, I just merged it. thanks!
